before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -s -w
      - -X {{.ModulePath}}/pkg/build.buildVersion={{.Version}}
      - -X {{.ModulePath}}/pkg/build.buildCommit={{.FullCommit}}
      - -X {{.ModulePath}}/pkg/build.buildDate={{.Date}}
      - -X {{.ModulePath}}/pkg/build.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features and enhancements
      regexp: '^.*?Feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?Bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?Docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
